 version: 2
 jobs:
   build:
     branch:
       only: 
         - master
         - develop
         - staging
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A first hello"
       
